app.py
=> fix: copy to say predict image

app.py
=> add meta tags for social apps

muse/ui/src/components/OverlayLoader.tsx
=> Update Modal message

.github/workflows/ci-testing.yml, tests/test_app_gallery.py
Adds e2e testing for Muse App:
- Tests the toggle button for fast image generation and high quality generation.
- Makes sure that the output image has opacity 1.0.
- Enters a new prompt.
These tests are used to keep track of gallery apps (internally). A user can also run them by installing `playwright`:
```bash
pip install playwright
playwright install
pytest tests/test_app_gallery.py --capture=no -v
```
Closes #175
=> Enable gallery e2e tests

app.py
=> Start handling requests when one model server is ready

muse/components/load_balancer.py, muse/utility/data_io.py
=> add global request count

.github/workflows/deploy.yml, muse/CONST.py, muse/__about__.py, muse/components/load_balancer.py
=> Basic authentication for Private endpoints

.github/workflows/deploy.yml
=> fix: deploy by enquoting "MUSE_SYSTEM_PASSWORD"

muse/components/muse_slack_bot.py
=> fix payload

tests/requirements.txt
fixes https://github.com/Lightning-AI/gallery-e2e-monitoring/actions/runs/3256790232/jobs/5347615500
=> add requiremtns in tests

app.py
=> update api component to new schema, dream to prompt

muse/CONST.py, muse/components/load_balancer.py
=> fix: update servers not working

.github/workflows/deploy.yml
It will be activated from [here](https://github.com/Lightning-AI/stable-diffusion-deploy/blob/main/muse/components/load_balancer.py#L144)
=> integrate sentry for performance and error monitoring

.github/workflows/ci-testing.yml, app.py, muse/components/muse_slack_bot.py, muse/utility/data_io.py, requirements.txt, tests/test_app_gallery.py
=> Fix gallery tests for 1.8

muse/pipeline/data.py, muse/pipeline/model.py, requirements.txt
=> Update for lightning 1.8 release

muse/components/safety_checker_embedding.py, muse/components/stable_diffusion_serve.py, requirements.txt
=> Remove Flash dependency & workaround fix for BuildConfig

dev_install.sh
=> remove flash requirement from dev installation

muse/components/stable_diffusion_serve.py
=> fp16 only with cuda

app.py
Don't start the initial servers with the flow (needed as they have random names which we rely on the state to track, but state is empty when the app starts in the cloud so the work gets lost)
**only affects launching from the CLI, gallery clone'n'run is fine**
=> Fix extra work when running from CLI

.lightningignore, dev_install.sh, muse/CONST.py, muse/components/stable_diffusion_serve.py, muse/pipeline/model.py
=> migrate to SD 2.0

.lightningignore, muse/CONST.py, muse/components/stable_diffusion_serve.py, muse/pipeline/model.py
=> Optimization

muse/CONST.py, muse/components/load_balancer.py, muse/components/stable_diffusion_serve.py
Rollback since received bad feedback for images generated with SD 2.0
=> Revert to Stable Diffusion 1

README.md, dev_install.sh, docs/configurations.md, muse/components/stable_diffusion_serve.py
=> clean docs

app.py, muse/components/load_balancer.py
Implements ready. **Note: Leaving the progress bar in for re-deployments**
=> Implement `ready`

muse/ui/package.json, muse/ui/yarn.lock
=> fix: use public https URL to install Lightning UI

.pre-commit-config.yaml, requirements.txt
=> upgrade to lightning 1.9

muse/components/load_balancer.py, muse/components/safety_checker_embedding.py
=> reduce cost

.github/workflows/ci-checks.yml
=> ci: update checks

requirements.txt, requirements/test.txt, tests/requirements.txt
We have to have `python-dotenv` and `uvloop` installed, but after the most recent Lightning release, we don't install them indirectly anymore. This PR just adds the requirements.
=> Adding python-dotenv and uvloop into requirements

tests/requirements.txt
=> Delete duplicate test requirements
